#
# Note: for tensorflow-text please check the base-notebook.ipynb
#
name: ml
channels:
  - apple
dependencies:
  - pip=23.1
  - python=3.10
  - jupyter=1.0.0
  - keras-tuner=1.3.5
  - shap=0.42.1
  - pip:
    - so-ml-tools
    - tensorflow-macos==2.12
    - tensorflow-metal==0.8.0
    - tensorflow-hub==0.14.0
    - tensorflow-datasets==4.9.2
    - opendatasets==0.1.22
    - opencv-python==4.8.0.76